### PR TITLE
RFC: Temporal Filter

### PR DESCRIPTION
**Pull request by fuyufjh**
Preview: https://github.com/risingwavelabs/rfcs/blob/eric/0018-temporal-filter/rfcs/0018-temporal-filter.md

Migrated from https://singularity-data.quip.com/a6XXAQVa6b0N/RFC-Temporal-Filter

### CODE REVIEW

**Comment by soundOfDestiny** [comment]
Seems that we will add a new field `time_now` in our barrier.
Do we want to collect one result per barrier, or collect multiple results per barrier?
- If we collect one result per barrier, we must ensure that the `time_now` is greater than watermark, or the result will be meaningless.
- If we collect multiple results per barrier, should we produce `2N` results per barrier (given that `N` is num of different value in time column recently) or produce `M` results per barrier (given that `M` is num of barriers recently)?

**Comment by jon-chuang** [comment]
Since we are doing a range delete for `TemporalFilter`, we should definitely use the delete range   interface (https://github.com/risingwavelabs/risingwave/issues/5978) for better performance.

**Comment by jon-chuang** [comment]
@soundOfDestiny , am I wrong, or is `time_now` equivalent to the watermark? It seems we should issue `time_now` from meta, and ensure that all of the barriers of same epoch have the same `time_now`?

**Comment by soundOfDestiny** [comment]
> @soundOfDestiny , am I wrong, or is `time_now` equivalent to the watermark? It seems we should issue `time_now` from meta, and ensure that all of the barriers of same epoch have the same `time_now`?

yes, I think that we should issue `time_now` from meta, and ensure that this `time_now` is greater than any watermark in source.

**Comment by soundOfDestiny** [comment]
> @soundOfDestiny , am I wrong, or is `time_now` equivalent to the watermark? It seems we should issue `time_now` from meta, and ensure that all of the barriers of same epoch have the same `time_now`?

yes, I think that we should issue `time_now` from meta, and ensure that this time_now is less than latest watermark in each shard of source.

**Comment by jon-chuang** [comment]
Will we also include an operator `insertion_time(t)` where t is table name?

So, for instance, 
```SQL
CREATE MATERIALIZED VIEW v AS SELECT * FROM t1 NATURAL JOIN t2 WHERE insertion_time(t1) > now() - '1h' AND insertion_time(t2) > now() - '15m'
```

**Comment by jon-chuang** [comment]
> time_now is less than latest watermark in each shard of source.

By watermark, you are referring to compaction watermark? Or watermark used in watermark filter?

**Comment by soundOfDestiny** [comment]
> > time_now is less than latest watermark in each shard of source.
> 
> By watermark, you are referring to compaction watermark? Or watermark used in watermark filter?

watermark used in watermark filter

**Comment by fuyufjh** [comment]
> Seems that we will add a new field time_now in our barrier.

It's Optional. The epoch (int64) is designed to carry physical time with higher bits in it.

> Do we want to collect one result per barrier, or collect multiple results per barrier?

Do you mean when to emit results? In my mind, if an event arrives and satisfies the time condition, it will be passed to downstream immediately. But the shifting of time is driven by barrier, so when the barriers some, some `DELETE` events may be emitted to delete the events that not satisfied the temporal filter condition any more.

**Comment by fuyufjh** [comment]
> Note that in this schemem, state cleaning and emitting `delete` events are independent. State cleanning is driven by `Watermark` message, that is, the events below the watermark will be removed from state. Emitting `delete` (or `insert`) events is driven by `Barrier` message, because the epoch in barriers will advance the current time (`now()`) and then trigger new `delete` or `insert` events to downsteam.

**Comment by soundOfDestiny** [comment]
> > Seems that we will add a new field time_now in our barrier.
> 
> It's Optional. The epoch (int64) is designed to carry physical time with higher bits in it.
> 
> > Do we want to collect one result per barrier, or collect multiple results per barrier?
> 
> Do you mean when to emit results? In my mind, if an event arrives and satisfies the time condition, it will be passed to downstream immediately. But the shifting of time is driven by barrier, so when the barriers some, some `DELETE` events may be emitted to delete the events that not satisfied the temporal filter condition any more.

I'm not sure the result at the barrier point it meaningful because it does not contain all data before `time_now`.

**Comment by jon-chuang** [comment]
> Either introducing a new TemporalFilter operator or reusing DynamicFilter looks good to me. Let's leave the choice to the implementer.

I think regardless, I'd prefer the use of now() emitting watermark, as that means that something downstream of the Dynamic/TemporalFilter can also clean its state based on the filter's timestamp field.

**Comment by soundOfDestiny** [comment]
> > Either introducing a new TemporalFilter operator or reusing DynamicFilter looks good to me. Let's leave the choice to the implementer.
> 
> I think regardless, I'd prefer the use of now() emitting watermark, as that means that something downstream of the Dynamic/TemporalFilter can also clean its state based on the filter's timestamp field.

yes, it will.

**Comment by fuyufjh** [comment]
It seems to be completed, right? Let's approve and merge it. cc. @soundOfDestiny @jon-chuang

**Comment by jon-chuang** [comment]
@fuyufjh We have yet to add e2e test and also missing forward of Watermark on Project operator (used for expressions of form `now() +- interval`) https://github.com/risingwavelabs/risingwave/issues/6790

**Review by soundOfDestiny — APPROVED** [review]
sadly introducing watermark will still meet `todo!` panic in our executors

**Comment by soundOfDestiny** [comment]
Datatype of `now()` in batch and in streaming are now both implemented as `Timestamptz`.
`now()` in streaming will return time of the barrier epoch.
`now()` in batch will return time of the latest epoch that the binder saw.

**Pull request merged**
