### PR TITLE
RFC: A new schedule way for distributed lookup join

### PR DESCRIPTION
**Pull request by chenzl25**

### CODE REVIEW

**Comment by liurenjie1024** [comment]
I have an optimization to this, for distributed lookup join, we can add an exchange to the build side(outer side):
```
LookupJoin
   HashExchange(key = index)
       IndexTable
```

And the lookup join needs to buffer all data from index table. This is quite similar to dynamic filter approach, and there are several advantages:
1. We can avoid sending scan tasks to all inner table when build side is not large.
2. Compare to current approach, we also avoid sending duplicate task same vnode in primary table.

**Comment by liurenjie1024** [comment]
Per offline discussion, we agree that we can use this proposal for now.

**Review by liurenjie1024 — APPROVED** [review]

**Comment by skyzh** [comment]
I feel like this is the same idea as my proposed streaming delta join. We should push data instead of doing remote lookup. If we can make this possible, it will probably also be easier for us to re-enable streaming delta join (as now we have upstream hash shard information in optimizer).

**Comment by skyzh** [comment]
... and the overall design looks great to me!

**Pull request merged**
