### PR TITLE
RFC: Better pretty printing for SQL explain

### PR DESCRIPTION
**Pull request by ice1000**
Demo: risinglightdb/risinglight#771
Main implementation: risingwavelabs/risingwave#10492

[Rendered](https://github.com/risingwavelabs/rfcs/blob/0672419e20dbd14e257c33a3f2f6f2a9f5a1414e/rfcs/0029-pretty.md)

### CODE REVIEW

**Review by xxchan — APPROVED** [review]
What's your implementation schedule? 🤩

**Comment by ice1000** [comment]
> What's your implementation schedule? 🤩

I have a very important thing to do in this month and I'll start right in March

**Comment by ice1000** [comment]
Merge? Since https://github.com/risingwavelabs/risingwave/pull/8576 is merged

**Comment by xxchan** [comment]
Only `stream_dist_plan` is changed now, what about other plans? 👀

**Comment by ice1000** [comment]
> Only `stream_dist_plan` is changed now, what about other plans? 👀

I will do them soon. Okay it seems that you're asking me to overhaul everything before I can get this merged 🤣

**Comment by ice1000** [comment]
> Only `stream_dist_plan` is changed now, what about other plans? 👀

Should we merge this now?

**Comment by ice1000** [comment]
Since the PRs are all merged I think it's good to go

**Pull request merged**
